#!/usr/bin/env python3
import skilstak.colors as c

def plain():
    print(c.rc() + "hello world", end  = ":|")
def multi():
    print(c.multi("helo werld")) 
    

if __name__ == "__main__":

    plain()
    multi()
    plain()


    
